import React from 'react';
import logo from './logo.svg';
import './App.css';
import RainbowScrollBar from './components/RainbowScrollBar';

function App() {
  return (
    <div className="App">
      <RainbowScrollBar />
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu malesuada quam, a consequat tortor. Aenean feugiat rutrum neque. Quisque bibendum risus est, id vestibulum dui suscipit ac. Praesent viverra egestas nunc ac varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam vel arcu a nisi lobortis fringilla a in mauris. Donec non tempus magna. Nunc lacinia, felis a facilisis congue, justo tellus interdum purus, id vehicula sem metus nec sapien. Morbi eget blandit odio. Ut ligula augue, aliquet eget scelerisque vel, blandit sit amet eros.

				Quisque quis turpis nec diam auctor facilisis non id quam. Nunc ultricies sem velit, sit amet ullamcorper risus rhoncus id. Nulla pellentesque, mi id varius fermentum, velit urna gravida dolor, nec aliquam quam neque quis leo. Duis nec ex volutpat, convallis risus vitae, consequat enim. Donec ut leo fringilla, pretium purus non, accumsan felis. Donec mattis metus eu nisi bibendum dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam venenatis felis ac pretium aliquet.
				
				Cras consequat sollicitudin odio at vestibulum. Vivamus vestibulum sed massa quis finibus. Etiam vitae purus bibendum, ornare velit vitae, laoreet dolor. Nunc vestibulum eu nibh eget feugiat. Nunc consectetur sit amet felis vitae fermentum. Mauris cursus velit sit amet quam interdum, eleifend ornare ex sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut semper est. Nunc elementum volutpat arcu sed egestas. Integer convallis ligula ante, et eleifend diam imperdiet et. Integer at sollicitudin arcu. Mauris vitae dictum est. Nulla ex libero, imperdiet quis ligula ac, fringilla mattis eros. Phasellus ultricies vitae odio vel feugiat.
				
				Sed cursus fringilla sem feugiat finibus. Donec vitae urna enim. Vestibulum at pulvinar neque. Nulla sodales scelerisque risus, in tempor nibh lobortis vel. Nunc bibendum elit nec elementum cursus. Nam at dignissim est. Fusce quis odio vitae quam condimentum fermentum porta id lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam tincidunt ultrices nibh, a accumsan augue. Vivamus eleifend, mi non tempor interdum, mauris neque maximus mi, non dapibus lorem nibh eu est. Donec ornare elit varius, tempus massa a, feugiat ante. Praesent sed mattis velit, ornare rhoncus tortor. Vestibulum mollis diam sit amet finibus laoreet.
				
				Fusce et felis arcu. Donec vestibulum cursus blandit. Praesent sem diam, fermentum sit amet lorem a, molestie feugiat enim. Sed at sollicitudin leo, ac cursus felis. Ut vel fringilla ante. Donec auctor, sem ut elementum dictum, tortor est mattis mi, euismod molestie lorem metus a ligula. Cras faucibus congue leo, quis gravida ipsum venenatis ut. Proin at egestas urna. Nulla varius ut neque fringilla tincidunt. Sed vel eleifend nunc. Sed accumsan dui quis tellus iaculis semper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu malesuada quam, a consequat tortor. Aenean feugiat rutrum neque. Quisque bibendum risus est, id vestibulum dui suscipit ac. Praesent viverra egestas nunc ac varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam vel arcu a nisi lobortis fringilla a in mauris. Donec non tempus magna. Nunc lacinia, felis a facilisis congue, justo tellus interdum purus, id vehicula sem metus nec sapien. Morbi eget blandit odio. Ut ligula augue, aliquet eget scelerisque vel, blandit sit amet eros.

				Quisque quis turpis nec diam auctor facilisis non id quam. Nunc ultricies sem velit, sit amet ullamcorper risus rhoncus id. Nulla pellentesque, mi id varius fermentum, velit urna gravida dolor, nec aliquam quam neque quis leo. Duis nec ex volutpat, convallis risus vitae, consequat enim. Donec ut leo fringilla, pretium purus non, accumsan felis. Donec mattis metus eu nisi bibendum dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam venenatis felis ac pretium aliquet.
				
				Cras consequat sollicitudin odio at vestibulum. Vivamus vestibulum sed massa quis finibus. Etiam vitae purus bibendum, ornare velit vitae, laoreet dolor. Nunc vestibulum eu nibh eget feugiat. Nunc consectetur sit amet felis vitae fermentum. Mauris cursus velit sit amet quam interdum, eleifend ornare ex sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut semper est. Nunc elementum volutpat arcu sed egestas. Integer convallis ligula ante, et eleifend diam imperdiet et. Integer at sollicitudin arcu. Mauris vitae dictum est. Nulla ex libero, imperdiet quis ligula ac, fringilla mattis eros. Phasellus ultricies vitae odio vel feugiat.
				
				Sed cursus fringilla sem feugiat finibus. Donec vitae urna enim. Vestibulum at pulvinar neque. Nulla sodales scelerisque risus, in tempor nibh lobortis vel. Nunc bibendum elit nec elementum cursus. Nam at dignissim est. Fusce quis odio vitae quam condimentum fermentum porta id lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam tincidunt ultrices nibh, a accumsan augue. Vivamus eleifend, mi non tempor interdum, mauris neque maximus mi, non dapibus lorem nibh eu est. Donec ornare elit varius, tempus massa a, feugiat ante. Praesent sed mattis velit, ornare rhoncus tortor. Vestibulum mollis diam sit amet finibus laoreet.
				
				Fusce et felis arcu. Donec vestibulum cursus blandit. Praesent sem diam, fermentum sit amet lorem a, molestie feugiat enim. Sed at sollicitudin leo, ac cursus felis. Ut vel fringilla ante. Donec auctor, sem ut elementum dictum, tortor est mattis mi, euismod molestie lorem metus a ligula. Cras faucibus congue leo, quis gravida ipsum venenatis ut. Proin at egestas urna. Nulla varius ut neque fringilla tincidunt. Sed vel eleifend nunc. Sed accumsan dui quis tellus iaculis semper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu malesuada quam, a consequat tortor. Aenean feugiat rutrum neque. Quisque bibendum risus est, id vestibulum dui suscipit ac. Praesent viverra egestas nunc ac varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam vel arcu a nisi lobortis fringilla a in mauris. Donec non tempus magna. Nunc lacinia, felis a facilisis congue, justo tellus interdum purus, id vehicula sem metus nec sapien. Morbi eget blandit odio. Ut ligula augue, aliquet eget scelerisque vel, blandit sit amet eros.

				Quisque quis turpis nec diam auctor facilisis non id quam. Nunc ultricies sem velit, sit amet ullamcorper risus rhoncus id. Nulla pellentesque, mi id varius fermentum, velit urna gravida dolor, nec aliquam quam neque quis leo. Duis nec ex volutpat, convallis risus vitae, consequat enim. Donec ut leo fringilla, pretium purus non, accumsan felis. Donec mattis metus eu nisi bibendum dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam venenatis felis ac pretium aliquet.
				
				Cras consequat sollicitudin odio at vestibulum. Vivamus vestibulum sed massa quis finibus. Etiam vitae purus bibendum, ornare velit vitae, laoreet dolor. Nunc vestibulum eu nibh eget feugiat. Nunc consectetur sit amet felis vitae fermentum. Mauris cursus velit sit amet quam interdum, eleifend ornare ex sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut semper est. Nunc elementum volutpat arcu sed egestas. Integer convallis ligula ante, et eleifend diam imperdiet et. Integer at sollicitudin arcu. Mauris vitae dictum est. Nulla ex libero, imperdiet quis ligula ac, fringilla mattis eros. Phasellus ultricies vitae odio vel feugiat.
				
				Sed cursus fringilla sem feugiat finibus. Donec vitae urna enim. Vestibulum at pulvinar neque. Nulla sodales scelerisque risus, in tempor nibh lobortis vel. Nunc bibendum elit nec elementum cursus. Nam at dignissim est. Fusce quis odio vitae quam condimentum fermentum porta id lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam tincidunt ultrices nibh, a accumsan augue. Vivamus eleifend, mi non tempor interdum, mauris neque maximus mi, non dapibus lorem nibh eu est. Donec ornare elit varius, tempus massa a, feugiat ante. Praesent sed mattis velit, ornare rhoncus tortor. Vestibulum mollis diam sit amet finibus laoreet.
				
				Fusce et felis arcu. Donec vestibulum cursus blandit. Praesent sem diam, fermentum sit amet lorem a, molestie feugiat enim. Sed at sollicitudin leo, ac cursus felis. Ut vel fringilla ante. Donec auctor, sem ut elementum dictum, tortor est mattis mi, euismod molestie lorem metus a ligula. Cras faucibus congue leo, quis gravida ipsum venenatis ut. Proin at egestas urna. Nulla varius ut neque fringilla tincidunt. Sed vel eleifend nunc. Sed accumsan dui quis tellus iaculis semper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu malesuada quam, a consequat tortor. Aenean feugiat rutrum neque. Quisque bibendum risus est, id vestibulum dui suscipit ac. Praesent viverra egestas nunc ac varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam vel arcu a nisi lobortis fringilla a in mauris. Donec non tempus magna. Nunc lacinia, felis a facilisis congue, justo tellus interdum purus, id vehicula sem metus nec sapien. Morbi eget blandit odio. Ut ligula augue, aliquet eget scelerisque vel, blandit sit amet eros.

				Quisque quis turpis nec diam auctor facilisis non id quam. Nunc ultricies sem velit, sit amet ullamcorper risus rhoncus id. Nulla pellentesque, mi id varius fermentum, velit urna gravida dolor, nec aliquam quam neque quis leo. Duis nec ex volutpat, convallis risus vitae, consequat enim. Donec ut leo fringilla, pretium purus non, accumsan felis. Donec mattis metus eu nisi bibendum dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam venenatis felis ac pretium aliquet.
				
				Cras consequat sollicitudin odio at vestibulum. Vivamus vestibulum sed massa quis finibus. Etiam vitae purus bibendum, ornare velit vitae, laoreet dolor. Nunc vestibulum eu nibh eget feugiat. Nunc consectetur sit amet felis vitae fermentum. Mauris cursus velit sit amet quam interdum, eleifend ornare ex sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut semper est. Nunc elementum volutpat arcu sed egestas. Integer convallis ligula ante, et eleifend diam imperdiet et. Integer at sollicitudin arcu. Mauris vitae dictum est. Nulla ex libero, imperdiet quis ligula ac, fringilla mattis eros. Phasellus ultricies vitae odio vel feugiat.
				
				Sed cursus fringilla sem feugiat finibus. Donec vitae urna enim. Vestibulum at pulvinar neque. Nulla sodales scelerisque risus, in tempor nibh lobortis vel. Nunc bibendum elit nec elementum cursus. Nam at dignissim est. Fusce quis odio vitae quam condimentum fermentum porta id lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam tincidunt ultrices nibh, a accumsan augue. Vivamus eleifend, mi non tempor interdum, mauris neque maximus mi, non dapibus lorem nibh eu est. Donec ornare elit varius, tempus massa a, feugiat ante. Praesent sed mattis velit, ornare rhoncus tortor. Vestibulum mollis diam sit amet finibus laoreet.
				
				Fusce et felis arcu. Donec vestibulum cursus blandit. Praesent sem diam, fermentum sit amet lorem a, molestie feugiat enim. Sed at sollicitudin leo, ac cursus felis. Ut vel fringilla ante. Donec auctor, sem ut elementum dictum, tortor est mattis mi, euismod molestie lorem metus a ligula. Cras faucibus congue leo, quis gravida ipsum venenatis ut. Proin at egestas urna. Nulla varius ut neque fringilla tincidunt. Sed vel eleifend nunc. Sed accumsan dui quis tellus iaculis semper.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu malesuada quam, a consequat tortor. Aenean feugiat rutrum neque. Quisque bibendum risus est, id vestibulum dui suscipit ac. Praesent viverra egestas nunc ac varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam vel arcu a nisi lobortis fringilla a in mauris. Donec non tempus magna. Nunc lacinia, felis a facilisis congue, justo tellus interdum purus, id vehicula sem metus nec sapien. Morbi eget blandit odio. Ut ligula augue, aliquet eget scelerisque vel, blandit sit amet eros.

				Quisque quis turpis nec diam auctor facilisis non id quam. Nunc ultricies sem velit, sit amet ullamcorper risus rhoncus id. Nulla pellentesque, mi id varius fermentum, velit urna gravida dolor, nec aliquam quam neque quis leo. Duis nec ex volutpat, convallis risus vitae, consequat enim. Donec ut leo fringilla, pretium purus non, accumsan felis. Donec mattis metus eu nisi bibendum dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam venenatis felis ac pretium aliquet.
				
				Cras consequat sollicitudin odio at vestibulum. Vivamus vestibulum sed massa quis finibus. Etiam vitae purus bibendum, ornare velit vitae, laoreet dolor. Nunc vestibulum eu nibh eget feugiat. Nunc consectetur sit amet felis vitae fermentum. Mauris cursus velit sit amet quam interdum, eleifend ornare ex sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut semper est. Nunc elementum volutpat arcu sed egestas. Integer convallis ligula ante, et eleifend diam imperdiet et. Integer at sollicitudin arcu. Mauris vitae dictum est. Nulla ex libero, imperdiet quis ligula ac, fringilla mattis eros. Phasellus ultricies vitae odio vel feugiat.
				
				Sed cursus fringilla sem feugiat finibus. Donec vitae urna enim. Vestibulum at pulvinar neque. Nulla sodales scelerisque risus, in tempor nibh lobortis vel. Nunc bibendum elit nec elementum cursus. Nam at dignissim est. Fusce quis odio vitae quam condimentum fermentum porta id lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam tincidunt ultrices nibh, a accumsan augue. Vivamus eleifend, mi non tempor interdum, mauris neque maximus mi, non dapibus lorem nibh eu est. Donec ornare elit varius, tempus massa a, feugiat ante. Praesent sed mattis velit, ornare rhoncus tortor. Vestibulum mollis diam sit amet finibus laoreet.
				
				Fusce et felis arcu. Donec vestibulum cursus blandit. Praesent sem diam, fermentum sit amet lorem a, molestie feugiat enim. Sed at sollicitudin leo, ac cursus felis. Ut vel fringilla ante. Donec auctor, sem ut elementum dictum, tortor est mattis mi, euismod molestie lorem metus a ligula. Cras faucibus congue leo, quis gravida ipsum venenatis ut. Proin at egestas urna. Nulla varius ut neque fringilla tincidunt. Sed vel eleifend nunc. Sed accumsan dui quis tellus iaculis semper.</p>
      </header>
    </div>
  );
}

export default App;
